### ISSUE TITLE
String Comparison and Mathematical Expression together

### ISSUE THREAD

**Issue by noumanjamil16** [uklimaschewski/EvalEx#243] opened 2020-07-02 15:16 UTC
Any function for String comparison?
 Can we achieve anything like this  IF(("ABC"=="ABC")||(5>3)) ?
The custom string function gives us the opportunity to compare two strings, what I want is to compare multiple strings and also evaluate an expression with mathematical calculations.

**Comment by RobertZenz** [comment] 2020-07-02 20:34
Duplicate of #196.

**Closed by RobertZenz** 2020-07-02 20:34 UTC
