### ISSUE TITLE
Weird Boolean evaluation for Long attributes 

### ISSUE THREAD

**Issue by pandilwar504** [uklimaschewski/EvalEx#214] opened 2019-08-12 12:30 UTC
Great Library!! Only the following scenarios is bothering me. 

String expression = "((1565612699586 >= 5.5) && (1565612699586 <= 1565612687894))";
Expression e = new Expression(expression);
e.eval();

I have a test around this which always returns 1 i.e. TRUE  which should be 0 i.e. FALSE, 
The weird part is when I debug and evaluate the individual expression and then again create the same  expression object , it sometimes return 0 and sometimes 1

All other comparisons looks good like double, integer etc. 
This issue is blocking us to use this library :(

**Comment by RobertZenz** [comment] 2019-08-12 19:23
I'm very sure that this is a duplicate of #114.

I know that there are always questions coming up regarding that, but there is no good way of addressing this problem on the API level of EvalEx. One could increase the default precision, but that would only push the problem to more niche cases. Setting the unlimited precision by default does also no help, as *some* expressions then will fail.

The best I can think of right now is to extend the README, somewhere around the "Usage Examples" with a clear note that one should set a precision suitable for their tasks.

**Comment by pandilwar504** [comment] 2019-08-12 21:40
Thank you for the quick reply!
currently, I am comparing long, double, and integer, so for long we have max precision is 19 . 

Do you see any issue with this default setting for comparison with long, double  and integer?

**Comment by RobertZenz** [comment] 2019-08-13 19:59
With the current default setting you mean? Yes, definitely, it has a precision of 7 I believe. So what you want to do is create the expression and set a precision of 19, at least. I'd rather go with more, because if you have two large numbers and you do anything but comparing them, you might run into trouble there.

Unless you're doing something computive intensive here (and I can't think of an application were this would really matter), I'd suggest to go with the `MathContext.DECIMAL128`, as it will give you 34 digits to work with.

**Comment by pandilwar504** [comment] 2019-08-16 18:36
Thank you!!  Currently, we are gonna do just comparisons, so I will keep 19 :)

**Comment by RobertZenz** [comment] 2019-08-17 08:03
Great! If you don't have any further questions you can close this issue.

**Comment by RobertZenz** [comment] 2019-08-18 14:16
I've added a section to the README regarding the precision. Maybe that will help avoid confusion in the future.

**Closed by RobertZenz** 2019-08-18 14:16 UTC

**Comment by pandilwar504** [comment] 2019-08-18 14:41
Thank you !!
