### ISSUE TITLE
Problem with sqrt

### ISSUE THREAD

**Issue by iyersathya** [uklimaschewski/EvalEx#54] opened 2016-02-02 16:12 UTC
Hello Udo, 
Thank you producing such a useful library. 
I came across an issue where sqrt function is getting stuck in this loop.
do {
					ixPrev = ix;
					ix = ix.add(n.divide(ix)).shiftRight(1);
					// Give other threads a chance to work;
					Thread.yield();
				} while (ix.compareTo(ixPrev) != 0);

I ended up overriding the function with java's sqrtj implementation.

**Comment by uklimaschewski** [comment] 2016-02-02 16:13
Thank you for the feedback, can you give me an example expression that reproduces this?

**Comment by iyersathya** [comment] 2016-02-02 16:22
please try SRRT(24)

**Comment by iyersathya** [comment] 2016-02-02 16:23
My mistake, I think it will only work on perfect squares.

**Comment by squeek502** [comment] 2016-02-02 20:24
SQRT(24) seems to work fine for me. Adding

```
assertEquals("4.8989794", new Expression("SQRT(24)").eval().toPlainString());
```

to the [existing SQRT tests](https://github.com/uklimaschewski/EvalEx/blob/master/tests/com/udojava/evalex/TestEval.java#L131-L140) still passes.

**Comment by uklimaschewski** [comment] 2016-02-03 14:23
What kind of Java and machine are you using? I tested in on a 64bit Intel Windows machine, without problem.

**Comment by iyersathya** [comment] 2016-02-04 15:21
I am using mac pro (2.6 GHz Intel Core i7), Yes running junit tests on native machine works fine.
I am using Android's emulator on genymotion (ARM hypervisor), I also tried it on Samsung Galaxy 7 note ( ARM) and it gets stuck in a while loop. 
Since its android , it is running on Dalvik VM, and the code is Dex'ed Dalvik code.
`
do {
	ixPrev = ix;  
	ix = ix.add(n.divide(ix)).shiftRight(1);
	// Give other threads a chance to work;
	Thread.yield();
} while (ix.compareTo(ixPrev) != 0);
`
here's the loop result.
loop 1: 
ixPrev=ix=4
ix = 5
loop 2:
ixPrev = ix = 5;
ix = 4
loop 3:
ixPrev=ix=4
ix=5

Hope that helps.

**Comment by uklimaschewski** [comment] 2016-04-10 09:16
I have now tried out 4 different Android devices and 2 different emulator configurations, but I was unable to reproduce. I'll close this issue for now. If there is a way how I can reproduce this bug here, let me know.

**Closed by uklimaschewski** 2016-04-10 09:16 UTC
Labels: bug
