### ISSUE TITLE
bug eval 88-8

### ISSUE THREAD

**Issue by baimurzin** [uklimaschewski/EvalEx#46] opened 2015-10-14 01:43 UTC
Why is 88-8 = 8E+1 ?
77-7 = 7E+1, should be 70?

**Comment by squeek502** [comment] 2015-10-14 02:27
Duplicate of #43

> The scientific notation is not produced by EvalEx, it is a result of the `toString()` method of the `BigDecimal` class.
> You can use the `toPlainString()` method on the `BigDecimal` result to avoid the scientific notation.

**Closed** 2015-10-14 07:08 UTC
