### ISSUE TITLE
minus "-" doesn't work before Open Parentheses "("

### ISSUE THREAD

**Issue by kingdom2011** [uklimaschewski/EvalEx#76] opened 2016-07-05 21:23 UTC
first, you did a great job. your EvalEx is awsome. but there is one annoying thing. **-** doesn't work before **(**. below expressions are really common and used alot, but evalex can't handle it. and throws exception.
(-(5))
(-(5+3)+3)
that would be great if it could handle above expressions.

**Comment by squeek502** [comment] 2016-07-05 21:30
EvalEx currently does not have support for any unary operators (like `-`). See #36

Your examples could be modified to work by doing this instead:

`(0-(5))`
`(0-(5+3)+3)`

**Comment by kingdom2011** [comment] 2016-07-05 21:39
really good work around. thanks.

**Comment by uklimaschewski** [comment] 2016-07-23 13:19
I'll close this, as it is a duplicate of issue #36.

**Closed by uklimaschewski** 2016-07-23 13:19 UTC
