### ISSUE TITLE
Easier Absolute Value and Factorial

### ISSUE THREAD

**Issue by NumberC** [uklimaschewski/EvalEx#236] opened 2020-03-19 01:49 UTC
Hello! This is a feature request. Instead of having to write `FACT(x)` or `ABS(x)`, is it possible to add a feature where users can write `x!` or `|x|` and return the same result? I'm willing to help if needed. Thank you!

**Comment by RobertZenz** [comment] 2020-03-19 07:39
This is partially a duplicate of #126, which is concerned with right-hand unary operators, and maybe #180.

But I don't believe that there is a ticket for having an operator *around* the variable.

**Comment by RobertZenz** [comment] 2020-03-19 07:40
Oh, and to rehash previous discussions about this, the parser does not support either case as far as I am aware.

**Comment by uklimaschewski** [comment] 2020-03-22 09:28
I think this will be too complex to implement, especially that |a| Syntax is far off the map.

**Closed by uklimaschewski** 2020-03-22 09:28 UTC
Labels: enhancement

**Comment by uklimaschewski** [comment] 2021-05-26 09:08
Fixed with #257
