### ISSUE TITLE
Incorrect result with large numbers.

### ISSUE THREAD

**Issue by rishipo** [uklimaschewski/EvalEx#178] opened 2018-08-10 01:45 UTC
Hi Guys, 

I am trying to do some calculation with double, it giving me wrong result.

```
public static void main(String arg[]) {
		double a = 1.478991136359E12;
		double b = 1.478991135281E12;
		System.out.println("Double a[" + a + "] b[" + b + "] : a-b[" + (a - b) + "]");

		Expression expression = new Expression("A-B");
		BigDecimal B = new BigDecimal(b);
		BigDecimal A = new BigDecimal(a);
		expression = expression.with("A", A);
		expression.and("B", B);
		BigDecimal result = expression.eval();

		System.out.println("BigDecimal A[" + A + "] B[" + B + "] A-B using evalex [" + result + "]");
	}
```

Output 

```
Double a[1.478991136359E12] b[1.478991135281E12] : a-b[1078.0]
BigDecimal A[1478991136359] B[1478991135281] A-B using evalex [0]
```

**Comment by RobertZenz** [comment] 2018-08-10 06:52
Duplicate of #114.

**Closed** 2018-09-07 11:41 UTC
