### ISSUE TITLE
Features to add

### ISSUE THREAD

**Issue by dovahkiin98** [uklimaschewski/EvalEx#169] opened 2018-05-20 10:08 UTC
It's a great engine, only one that I found that uses BigDecimal for numbers.
Tho it needs many features, I'm comparing it with the old Arity by Google.

- ! Operator (Fact)
- √ Operator (square root)
- π Number (Pi)
- log2 Function (Log_2)
- ln Function (log_e)
- Easily switch between Degree and Radians
- Evaluate "sin(0" without need for closing parenthesis
- Null safety for Kotlin
- Infinity and NaN detection (instead of throwing exception)
- pi(2+1), here pi is treated as a function
- Support for × and ÷ operators

I'm ready to help in any way I can

**Comment by RobertZenz** [comment] 2018-05-22 11:20
> * ! Operator (Fact)
 > * √ Operator (square root)
 > * π Number (Pi)
 > * log2 Function (Log_2)
 > * ln Function (log_e)
 > Support for × and ÷ operators

All of these seem to be rather straightforward to add, the default functions are added in the constructor of `Expression`.

 > Easily switch between Degree and Radians

Do you mean *converting* between these, or do you mean that functions like `sin` should expect the other units?

 > Evaluate "sin(0" without need for closing parenthesis

Ugh. That sounds like a mess, for example the following expressions are valid, but not equal:

    sin(0.45) + 10
    sin(0.45 + 10)
    sin(0.45 + 10

That seems to me more like a syntax error which is erroneously accepted.

 > Null safety for Kotlin

Care to elaborate?

 > Infinity and NaN detection (instead of throwing exception)

Well, what else is EvalEx supposed to do in that case?

 > pi(2+1), here pi is treated as a function

Huh? I don't get it.

**Comment by dovahkiin98** [comment] 2018-05-22 13:21
in switching between DEG and RAD I mean like sin(pi) should return 0 if the developer wishes to use RAD instead of DEG.

sin(0.45 + 10
and
sin(0.45 + 10)
should be equal, but that's not equal to sin(0.45) + 10. I know it's hard to implement, but most calculator apps don't always expect a left ).

When evaluating 1/0 the EvalEx throws an exception instead of returning NaN, same with ln(0).

pi(2+1) is supposed to be equal to 9.42... but instead the EvalEx expects pi to be a function while it's the number pi.

Also, did you consider using Java 8? or at least Java 7, Java 6 is very old now, and I was wondering why you're using Java 6.

**Comment by RobertZenz** [comment] 2018-05-22 13:42
> in switching between DEG and RAD I mean like sin(pi) should return 0 if the developer wishes to use RAD instead of DEG.

I'm not sure whether that fits into the default functionality. It can be easily added in the project that uses EvalEx, though.

 > When evaluating 1/0 the EvalEx throws an exception instead of returning NaN, same with ln(0).

`BigDecimal` does not have a concept of `NaN`, at least not as far as I'm aware. So `eval(...)` would need to return something like `null`, which is quite bad speaking from an API design perspective. Because the return value `null` must be defined as "could not be evaluated for *some* reason", which is way worse than throwing an exception with the appropriate message/reason.

 > pi(2+1) is supposed to be equal to 9.42... but instead the EvalEx expects pi to be a function while it's the number pi.

Where is this coming from? Because `pi*(2+1)` seems just as easy.

 > Also, did you consider using Java 8? or at least Java 7, Java 6 is very old now, and I was wondering why you're using Java 6.

As far as I know, the goal is to provide a library that just works, that means having support for Java 6. Also, what would one gain from using Java 8? The API would not change in any meaningful way and the current code structure is acceptable and would also not change in any meaningful way (except the default functions, I'm still trying to come up with a better way to structure that, for example introducing something like a scope). The downside of using Java 8 is that this cannot be used for any projects that are not Java 8.

**Comment by dilworks** [comment] 2018-08-06 16:02
The problem is that Java 6 is no longer supported, and Java 7 is only supported if you're willing to pay Mucho Dinero™ to Oracle for a support contract (IIRC they don't even offer such old JDKs for public downloads without jumping a few hoops). Those would be the main reasons for raising the bar to Java 8, which is the oldest supported version for now.

Aside of that... well, there are no other reasons. I'm still getting used to the new stuff on Java 8 (lambdas and all that "functional programming" stuff), so I understand that sometimes keeping it simple is the better way.

**Comment by vanniktech** [comment] 2018-09-02 12:33
>> Null safety for Kotlin

> Care to elaborate?

This can easily done by annotation parameters and return types with `@NonNull` / `@NotNull` annotations or `@Nullable`.

>> ! Operator (Fact)
√ Operator (square root)
π Number (Pi)
log2 Function (Log_2)
ln Function (log_e)
Support for × and ÷ operators

> All of these seem to be rather straightforward to add, the default functions are added in the constructor of Expression.

Interested in this, if this is still wanted I can submit a PR.

**Comment by uklimaschewski** [comment] 2021-05-26 11:27
Several things already implemented, or possible to implement with custom operators.

**Closed by uklimaschewski** 2021-05-26 11:27 UTC
Labels: enhancement
